# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='db',
  serialized_pb=_b('\n\x08\x64\x62.proto\x12\x02\x64\x62\"<\n\nPlayerInfo\x12\x0e\n\x03uid\x18\x02 \x01(\x07:\x01\x30\x12\x0e\n\x04name\x18\x04 \x01(\t:\x00\x12\x0e\n\x03sex\x18\x05 \x01(\r:\x01\x30\"&\n\rL2D_ROLE_LIST\x12\x15\n\naccount_id\x18\x01 \x01(\x07:\x01\x30\"9\n\rD2L_ROLE_LIST\x12(\n\x10player_info_list\x18\x01 \x03(\x0b\x32\x0e.db.PlayerInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='db.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='db.PlayerInfo.uid', index=0,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='db.PlayerInfo.name', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='db.PlayerInfo.sex', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=76,
)


_L2D_ROLE_LIST = _descriptor.Descriptor(
  name='L2D_ROLE_LIST',
  full_name='db.L2D_ROLE_LIST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='db.L2D_ROLE_LIST.account_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=116,
)


_D2L_ROLE_LIST = _descriptor.Descriptor(
  name='D2L_ROLE_LIST',
  full_name='db.D2L_ROLE_LIST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_info_list', full_name='db.D2L_ROLE_LIST.player_info_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=175,
)

_D2L_ROLE_LIST.fields_by_name['player_info_list'].message_type = _PLAYERINFO
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['L2D_ROLE_LIST'] = _L2D_ROLE_LIST
DESCRIPTOR.message_types_by_name['D2L_ROLE_LIST'] = _D2L_ROLE_LIST

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFO,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.PlayerInfo)
  ))
_sym_db.RegisterMessage(PlayerInfo)

L2D_ROLE_LIST = _reflection.GeneratedProtocolMessageType('L2D_ROLE_LIST', (_message.Message,), dict(
  DESCRIPTOR = _L2D_ROLE_LIST,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.L2D_ROLE_LIST)
  ))
_sym_db.RegisterMessage(L2D_ROLE_LIST)

D2L_ROLE_LIST = _reflection.GeneratedProtocolMessageType('D2L_ROLE_LIST', (_message.Message,), dict(
  DESCRIPTOR = _D2L_ROLE_LIST,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.D2L_ROLE_LIST)
  ))
_sym_db.RegisterMessage(D2L_ROLE_LIST)


# @@protoc_insertion_point(module_scope)
